# Generated by Django 5.2.13 on 2026-04-30 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('physical_score', models.FloatField(blank=True, null=True)),
                ('psychological_score', models.FloatField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='monitoring.athlete')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_hours', models.FloatField()),
                ('meals', models.PositiveSmallIntegerField()),
                ('heart_rate_rest', models.PositiveSmallIntegerField()),
                ('heart_rate_load', models.PositiveSmallIntegerField()),
                ('recovery_time', models.FloatField(help_text='Recovery time in minutes as float, e.g. 2.5 for 2:30.')),
                ('fatigue', models.PositiveSmallIntegerField()),
                ('rpe', models.PositiveSmallIntegerField()),
                ('daily_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_data', to='monitoring.dailyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellbeing', models.PositiveSmallIntegerField()),
                ('activity', models.PositiveSmallIntegerField()),
                ('mood', models.PositiveSmallIntegerField()),
                ('daily_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychological_data', to='monitoring.dailyrecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('athlete', 'date'), name='unique_daily_record_per_athlete'),
        ),
    ]
