# Generated by Django 5.2.13 on 2026-04-30 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SANTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SANAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField()),
                ('value', models.SmallIntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='monitoring.santest')),
            ],
            options={
                'ordering': ['question_number'],
                'constraints': [models.UniqueConstraint(fields=('test', 'question_number'), name='unique_san_answer_per_question'), models.CheckConstraint(condition=models.Q(('value__gte', -3), ('value__lte', 3)), name='san_answer_value_between_minus_3_and_3'), models.CheckConstraint(condition=models.Q(('question_number__gte', 1), ('question_number__lte', 30)), name='san_question_number_between_1_and_30')],
            },
        ),
    ]
